### ISSUE TITLE
Import issues with typescript (using Vscode insiders and typescript 2.7.0 dev build)

### ISSUE THREAD

**Issue by thaoula** [amcdnl/ngrx-actions#21] opened 2018-01-19 07:52 UTC
Hi, 

Firstly, thanks very much for this library.

I have a problem when using Vscode insider and importing items from your library.

When importing from 'ngrx-actions' typescript reports it cannot find the export. However, when importing form 'ngrx-actions/public_api' everything work fine.

Older versions of typescript dont have a problem but cannot correctly indent the arguments of the pipe method.

Regards,
Tarek

**Comment by thaoula** [comment] 2018-01-19 08:25
Just seems to affect intellisense. Using the working import above actually prevents builds.

Similar issue seems to affect LoadingBarHttpModule.

**Comment by amcdnl** [comment] 2018-01-20 16:13
I can't reproduce either.

**Comment by thaoula** [comment] 2018-01-21 06:49
Hi Guys,

Thanks for taking a look. This is what i get on vscode insiders (Mac)

![image](https://user-images.githubusercontent.com/349133/35191587-bef77d6e-feb1-11e7-8cda-fbe0695f79b3.png)

**Comment by amcdnl** [comment] 2018-01-21 16:43
Well TS 2.7 isn't even out yet, wonder if its an issue on their side seeing how stable isn't having issues?

**Comment by thaoula** [comment] 2018-01-22 02:22
Ok, I will file an issue with VScode.

I filed here because the issue is only affecting two libraries (ngrx-actions and LoadingBarHttpModule)

**Comment by amcdnl** [comment] 2018-01-25 16:49
Gonna close this for now, if its specific to our lib, feel free to reopen.

**Closed by amcdnl** 2018-01-25 16:49 UTC
Labels: need feedback

**Comment by thaoula** [comment] 2018-01-26 08:56
Hi, 

This problem is not going away, the latest version of typescript@next and latest CLI beta now report the same error as seen is VScode.

```
ERROR in libs/@shared/src/shared.module.ts(61,10): error TS2305: Module '"/Users/thaoula/Projects/Empower/jms-platform/jms-web/node_modules/ngx-chips/ngx-chips"' has no exported member 'TagInputModule'.
apps/jms/src/modules/application/application.module.ts(15,10): error TS2305: Module '"/Users/thaoula/Projects/Empower/jms-platform/jms-web/node_modules/@ngx-loading-bar/http/http"' has no exported member 'LoadingBarHttpModule'.
apps/jms/src/modules/application/application.module.ts(18,10): error TS2305: Module '"/Users/thaoula/Projects/Empower/jms-platform/jms-web/node_modules/ngrx-actions/ngrx-actions"' has no exported member 'NgrxActionsModule'.
apps/jms/src/modules/application/application.module.ts(18,29): error TS2305: Module '"/Users/thaoula/Projects/Empower/jms-platform/jms-web/node_modules/ngrx-actions/ngrx-actions"' has no exported member 'NgrxSelect'.
libs/ui.view.editor/src/view.editor.module.ts(4,10): error TS2305: Module '"/Users/thaoula/Projects/Empower/jms-platform/jms-web/node_modules/ngx-chips/ngx-chips"' has no exported member 'TagInputModule'.
apps/jms/src/modules/operations/state/operation.selectors.ts(1,10): error TS2305: Module '"/Users/thaoula/Projects/Empower/jms-platform/jms-web/node_modules/ngrx-actions/ngrx-actions"' has no exported member 'Select'.
apps/jms/src/modules/operations/state/operation.effects.ts(6,10): error TS2305: Module '"/Users/thaoula/Projects/Empower/jms-platform/jms-web/node_modules/ngrx-actions/ngrx-actions"' has no exported member 'ofAction'.
apps/jms/src/modules/operations/state/operation.effects.ts(42,46): error TS2339: Property 'viewId' does not exist on type '{}'.
apps/jms/src/modules/operations/state/operation.effects.ts(56,39): error TS2339: Property 'request' does not exist on type '{}'.
apps/jms/src/modules/operations/state/operation.effects.ts(98,42): error TS2339: Property 'isJob' does not exist on type '{}'.
apps/jms/src/modules/operations/state/operation.effects.ts(99,35): error TS2339: Property 'id' does not exist on type '{}'.
apps/jms/src/modules/operations/state/operation.effects.ts(100,32): error TS2339: Property 'id' does not exist on type '{}'.
apps/jms/src/modules/operations/state/operation.effects.ts(157,38): error TS2339: Property 'request' does not exist on type '{}'.
apps/jms/src/modules/operations/state/operation.effects.ts(180,54): error TS2339: Property 'request' does not exist on type '{}'.
apps/jms/src/modules/operations/state/operation.store.ts(1,10): error TS2305: Module '"/Users/thaoula/Projects/Empower/jms-platform/jms-web/node_modules/ngrx-actions/ngrx-actions"' has no exported member 'Store'.
apps/jms/src/modules/operations/state/operation.store.ts(1,17): error TS2305: Module '"/Users/thaoula/Projects/Empower/jms-platform/jms-web/node_modules/ngrx-actions/ngrx-actions"' has no exported member 'Action'.
apps/jms/src/modules/operations/state/operation.store.ts(1,25): error TS2305: Module '"/Users/thaoula/Projects/Empower/jms-platform/jms-web/node_modules/ngrx-actions/ngrx-actions"' has no exported member 'createReducer'. 
```

This error is also in the library. #https://github.com/aitboudad/ngx-loading-bar/issues/52

**Comment by thaoula** [comment] 2018-01-26 09:44
Reverted back to typescript 2.7.0-rc and imported like this 

import { Store } from 'ngrx-actions';
import { Action } from 'ngrx-actions';
import { createReducer } from 'ngrx-actions';

Now it builds, and VS does not complain.
